services:
  - type: web
    name: sistema-gestion-vuelos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sistema_gvqe
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /dashboard
    autoDeploy: true
    domains:
      - sistema-vuelos.onrender.com

databases:
  - name: sistema_gvqe
    databaseName: sistema_gvqe
    user: yova
    plan: free
