services:
  - type: web
    name: sistema-gestion-vuelos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      # CAMBIA ESTO: Usar tu nueva BD manual
      - key: DATABASE_URL
        value: postgresql://yova:j0smlHpbZTp1qgZsruJUHI9XW7Gv9gtt@dpg-d4u0hcfgi27c73a9b4rg-a.virginia-postgres.render.com/sistema_2tdl
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /dashboard
    autoDeploy: true
    domains:
      - sistema-vuelos.onrender.com


 databases:
   - name: sistema_gvqe
     databaseName: sistema_gvqe
     user: yova
     plan: free
