services:
  - type: web
    name: sistema-vuelos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vuelos_db
          property: connectionString
      - key: RENDER
        value: true
    autoDeploy: true

databases:
  - name: vuelos_db
    databaseName: vuelos
    user: vuelos_user
    plan: free
    
